#ifndef SVSCRAFTQUICKIMPLGLOBAL_H
#define SVSCRAFTQUICKIMPLGLOBAL_H

#include <QtGlobal>

#ifndef SVSCRAFT_QUICK_IMPL_EXPORT
#  ifdef SVSCRAFT_QUICK_IMPL_STATIC
#    define SVSCRAFT_QUICK_IMPL_EXPORT
#  else
#    ifdef SVSCRAFT_QUICK_IMPL_LIBRARY
#      define SVSCRAFT_QUICK_IMPL_EXPORT Q_DECL_EXPORT
#    else
#      define SVSCRAFT_QUICK_IMPL_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // SVSCRAFTQUICKIMPLGLOBAL_H

