#ifndef SVSCRAFT_SVSCRAFTFLUENTSYSTEMICONSGLOBAL_H
#define SVSCRAFT_SVSCRAFTFLUENTSYSTEMICONSGLOBAL_H

#include <QtGlobal>

#ifndef SVSCRAFT_FLUENT_SYSTEM_ICONS_EXPORT
#  ifdef SVSCRAFT_FLUENT_SYSTEM_ICONS_STATIC
#    define SVSCRAFT_FLUENT_SYSTEM_ICONS_EXPORT
#  else
#    ifdef SVSCRAFT_FLUENT_SYSTEM_ICONS_LIBRARY
#      define SVSCRAFT_FLUENT_SYSTEM_ICONS_EXPORT Q_DECL_EXPORT
#    else
#      define SVSCRAFT_FLUENT_SYSTEM_ICONS_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif //SVSCRAFT_SVSCRAFTFLUENTSYSTEMICONSGLOBAL_H
