#ifndef SVSCRAFTWIDGETSGLOBAL_H
#define SVSCRAFTWIDGETSGLOBAL_H

#include <QtGlobal>

#ifndef SVSCRAFT_WIDGETS_EXPORT
#  ifdef SVSCRAFT_WIDGETS_STATIC
#    define SVSCRAFT_WIDGETS_EXPORT
#  else
#    ifdef SVSCRAFT_WIDGETS_LIBRARY
#      define SVSCRAFT_WIDGETS_EXPORT Q_DECL_EXPORT
#    else
#      define SVSCRAFT_WIDGETS_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif // SVSCRAFTWIDGETSGLOBAL_H
